name: avaliacao_seven_pay
description: Avaliação Desenvolvedor 7PAY


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  http: ^0.13.5
  provider: ^6.1.2
  dropdown_button2: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/7pay_logo.png

  fonts:
    - family: Scorno
      fonts:
        - asset: assets/fonts/Rosario Nocera - Scorno demo heavy.otf
        - asset: assets/fonts/Rosario Nocera - Scorno demo Medium.otf

